# Generated by Django 3.1.4 on 2021-01-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=500)),
                ('categoryIconImg', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='imageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('large', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='productCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combinationString', models.CharField(max_length=500)),
                ('variationName', models.CharField(max_length=500)),
                ('availableStock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=500)),
                ('catName', models.CharField(max_length=500)),
                ('subCatName', models.CharField(max_length=500)),
                ('previewImg', models.ImageField(upload_to='pics')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='productVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationName', models.CharField(max_length=500)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
            ],
        ),
        migrations.CreateModel(
            name='subCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCatName', models.CharField(max_length=500)),
                ('catID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='productVariationOpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationName', models.CharField(max_length=500)),
                ('productVariationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation')),
            ],
        ),
        migrations.CreateModel(
            name='productStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.IntegerField()),
                ('totalStock', models.IntegerField()),
                ('productCombinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcombination')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='subCatID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcat'),
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFeatured', models.BooleanField(default=False)),
                ('imageGalleryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.imagegallery')),
                ('productVariationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariationopt')),
            ],
        ),
        migrations.AddField(
            model_name='productcombination',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products'),
        ),
    ]
