# Generated by Django 3.1.4 on 2021-01-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='previewImg',
            field=models.ImageField(upload_to=''),
        ),
    ]
