# Generated by Django 3.1.4 on 2021-01-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210112_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryIconImg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='previewImg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
