# Generated by Django 3.1.4 on 2021-01-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210112_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productSlug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
