# Generated by Django 3.1.4 on 2021-01-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_dailydeals'),
    ]

    operations = [
        migrations.CreateModel(
            name='seasonProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(max_length=50)),
                ('summer', models.CharField(max_length=50)),
                ('rainy', models.CharField(max_length=50)),
                ('all', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='dailydeals',
            options={'verbose_name_plural': 'daily deals'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='productName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='seasonID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.seasonproduct'),
            preserve_default=False,
        ),
    ]
