# Generated by Django 3.1.4 on 2021-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210125_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seasonName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
