# Generated by Django 3.1.4 on 2021-01-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_products_seasonname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombination',
            name='SKU',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcombination',
            name='uniqueStrID',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
